### ISSUE TITLE
请问一下可以开放一下下一曲还有播放暂停的控制api吗？

### ISSUE THREAD

**Issue by kptanjunhao** [wangpengfei15975/skPlayer#1]
请问一下可以加入一下下一曲还有播放暂停的控制api吗？谢谢大大0 0 。

**Comment by wangpengfei15975** [comment]
@kptanjunhao 只是需要api是吗？不改动UI的话这周末可以提供了。

**Comment by kptanjunhao** [comment]
对啊对啊0 0 。只要api     谢谢巨巨   🙏  用在个人blog上的。

**Comment by wangpengfei15975** [comment]
@kptanjunhao 周末好的吧？ = =

**Comment by kptanjunhao** [comment]
嗯嗯嗯嗯嗯 没关系的。多晚都OK。

**Comment by wangpengfei15975** [comment]
@kptanjunhao 抱歉，来晚了 =。= 新版已经改好了，结构推倒ES6重写，提供了海量API。我下午更新到github
