### ISSUE TITLE
网易云歌单无法获取，只能获取一个

### ISSUE THREAD

**Issue by chenhonzhou** [wangpengfei15975/skPlayer#11]
![deepinscreenshot_select-area_20171212084102](https://user-images.githubusercontent.com/30407568/33861316-349d7da2-df18-11e7-84c6-f2ec0a20b69c.png)

是否网易更新机制，或者为`Bug`

**Comment by wangpengfei15975** [comment]
@chenhonzhou 抱歉，接口出问题了，在修
