### ISSUE TITLE
OPERA浏览器无法播放音乐

### ISSUE THREAD

**Issue by MuddyEGG** [wangpengfei15975/skPlayer#12]
![tim 20180110075222](https://user-images.githubusercontent.com/30097710/34761326-45594776-f61e-11e7-8c78-26221fcbef19.png)

**Comment by wangpengfei15975** [comment]
是拉取的歌单吗？
看了下是网易云音乐返回的资源编码有问题

**Comment by MuddyEGG** [comment]
是的
这个问题可以修复吗

**Comment by wangpengfei15975** [comment]
最多可以处理资源无法播放的异常情况捕获，但是不能处理问题根源

**Comment by wangpengfei15975** [comment]
修复了 请下载最新版
