### ISSUE TITLE
你好。。关于苹果手机端，，获取歌曲总长度为NaN的问题怎么解决呀

### ISSUE THREAD

**Issue by ssqsunqin** [wangpengfei15975/skPlayer#14]

**Comment by wangpengfei15975** [comment]
抱歉 歌单拉取出现了问题 这周内修复

**Comment by ssqsunqin** [comment]
# @
![eca3b9ba8b285032279f36bd165c5389](https://user-images.githubusercontent.com/12098694/35320890-55fb59c4-00dd-11e8-9f18-cfe1d874bb6f.png)

**Comment by ssqsunqin** [comment]
苹果端，获取s.timeFormat(t.audio.duration),,获得的长度为NaN，，，pc端和安卓端是正常的，，苹果端如图所示，，，

**Comment by ssqsunqin** [comment]
@wangpengfei15975
