### ISSUE TITLE
update

### ISSUE THREAD

**Issue by ForeversayOK** [wangpengfei15975/skPlayer#4]
想要快点更新啊，买了个主机了迫不及待*٩(๑´∀`๑)ง*

**Comment by wangpengfei15975** [comment]
@ForeversayOK 好的，以前的代码太丑了，准备用ES6重写，所以可能要久一些 。。

**Comment by ForeversayOK** [comment]
嗯嗯好。

**Comment by wangpengfei15975** [comment]
@ForeversayOK 抱歉，来晚了 =。= 新版已经改好了，结构推倒ES6重写，提供了海量API。我下午更新到github

**Comment by ForeversayOK** [comment]
@wangpengfei15975 哈哈，弄代码是要慢一点的啦，支持你~
