### ISSUE TITLE
老大 能不能给加一个加载音乐的进度

### ISSUE THREAD

**Issue by yy584089958** [wangpengfei15975/skPlayer#5]
大佬  我发现 播放网易歌曲高品质的时候 有时候播到一半就卡主 断了 不知道是网络问题 还是音乐加载了一半，然后console报net::ERR_CONNECTION_RESET 或 net::ERR_CONTENT_LENGTH_MISMATCH [ opdays.com](opdays.com) 我看其他人的有加载进度 大佬这个加载进度是怎么要怎么实现

**Comment by wangpengfei15975** [comment]
@yy584089958 没毛病，加加加。因为最开始想比较简约，所以功能能少就少了。视频播放器我写过加载进度，跟音频的差不多。近期就开始重整、
