### ISSUE TITLE
当音乐资源失效时候处理

### ISSUE THREAD

**Issue by ihewro** [wangpengfei15975/skPlayer#9]
网易云的api获取的音乐有时候因为版权问题，获取到的音乐地址无法播放

希望能够当音乐地址无法播放的时候，增加一个抛出异常的接口，可以在这里写一些提示信息，切换到下一首歌曲

**Comment by wangpengfei15975** [comment]
@ihewro 
目前这个列表接口是可以播放无版权的歌，我列表中第17首就是无版权正常播放的。
你说的可能是网易云本身资源存在问题，我处理一下吧。
谢谢反馈 ~
